### ISSUE TITLE
re-design permission pre-check for froster index 

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/froster#93]
before `froster index` is submitted to cluster to do a parallel pwalk another function is  run :

_is_correct_files_folders_permissions

This function has 2 problems: 

- it is not run in parallel like pwalk and it can take weeks before pwalk will even get started 
- it is not capturing os.walk errors

**Comment by victormachadoperez** [comment]
You are right. This function uses os.walk but not pwalk, so it is unsuitable for large HPC systems.

```_is_correct_files_folders_permissions``` function has been deleted from froster {index|archive|delete|restore} commands for the same reason.

The function is not used but is still implemented in case we implement a "walk solution" in the future.

Wherever ```os.walk``` is used, it captures and prints the ```os.walk``` errors.

Also, I improved the print_error() output so it specifically captures PermissionError or "ReadError" and "WriteError" exceptions and leads the user to use ```froster archive --permissions /folder/path``` to check permission issues with a given folder. 

This is fixed in froster v0.14.5
